#!/bin/env bash

set -e
set -o pipefail

VERSION="$1"
ROOTDIR="$(dirname $(realpath $0))"
FLUTTER="$ROOTDIR/flutter"

#GIT_CDN="hub.gitmirror.com/"
BASE_URL="${GIT_CDN}https://github.com/mumumusuc/termux-flutter/releases/download"
BASE_RAW="${GIT_CDN}https://raw.githubusercontent.com/mumumusuc/termux-flutter/main"

command -v git > /dev/null 2>&1 || {
    >&2 echo
    >&2 echo 'Missing "git" tool.'
    >&2 echo 'Consider running "apt install git".'
    echo
    exit 1
}

command -v curl > /dev/null 2>&1 || {
    >&2 echo
    >&2 echo 'Missing "curl" tool.'
    >&2 echo 'Consider running "apt install curl".'
    echo
    exit 1
}

command -v python3 > /dev/null 2>&1 || {
    >&2 echo
    >&2 echo 'Missing "python3" tool.'
    >&2 echo 'Consider running "apt install python3".'
    echo
    exit 1
}

if [ -z "$VERSION" ]; then 
    VERSION=$(curl -fsSL "https://api.github.com/repos/mumumusuc/termux-flutter/releases/latest" | grep "tag_name" | sed 's|.*"tag_name"\ *:\ *"\([^"]*\)".*|\1|')
fi

curl -sSL "https://api.github.com/repos/mumumusuc/termux-flutter/releases/tags/$VERSION" | grep "\"tag_name\": \"$VERSION\"" > /dev/null || {
    if [ ${PIPESTATUS[0]} -eq 0 ]; then
        >&2 echo "Version \"$VERSION\" not found."
    fi
    exit 1
}

failure() {
    >&2 echo
    >&2 echo "Failed to retrieve file from: \"$1\""
    >&2 echo
    rm -f -- "$1"
    exit 1
}

download() {
    TAR="$1.tar.gz"
    SHA="$1.sha256"
    
    URL="$BASE_URL/$VERSION/$SHA" && curl -fsSLO $URL || { 
        failure $URL
    }

    sha256sum -c $SHA --status 2>/dev/null && {
        return 0
    }

    echo "Downloading $TAR ..."

    URL="$BASE_URL/$VERSION/$TAR" && curl -#fLO $URL --retry 3 --continue-at - || {
        failure $URL
    } && sha256sum -c $SHA --status || {
        >&2 echo "Sha256sum check failed, please try again."
        rm -f -- "$SHA"
        rm -f -- "$TAR"
        exit 1
    }
}

main() {
    echo "Got version \"$VERSION\"."

    URL="$BASE_RAW/install.py" && curl -fsSLO $URL || {
        failure $URL
    }
    download "engine"   
    download "dart-sdk"

    if [ ! -d $FLUTTER ]; then 
        git clone --depth=1 "https://www.github.com/flutter/flutter.git" -b $VERSION $FLUTTER
    fi
        
    TAG="$(git -C $FLUTTER describe --tags HEAD)" || {
        >&2 echo
        >&2 echo "Invalid flutter repo."
        >&2 echo "Try to remove $FLUTTER, or change to another directory"
        exit 1
    }
    
    if [ "$TAG" != "$VERSION" ]; then
        echo
        git -C $FLUTTER fetch --tags
        git -C $FLUTTER checkout $VERSION
    fi

    python3 install.py -d dart-sdk.tar.gz -e engine.tar.gz $FLUTTER

    echo
    $FLUTTER/bin/flutter doctor

    echo
    echo "Installation is complete. Now you can add \"$FLUTTER/bin\" into your PATH."
}

cd $TMPDIR && main "$@"
