#!/bin/env bash

set -e

TAG="$1"
REPO="termux-flutter"
OWNER="mumumusuc"
ASSET="${2:-release}"
TOKEN="$3"

echo "Fetching release $TAG."
ID=$(curl -s \
          -H "Authorization: token $TOKEN" \
          "https://api.github.com/repos/$OWNER/$REPO/releases/tags/$TAG" \
    | jq ".id")

if [ $ID == 'null' ]; then
echo "Creating new release $TAG."
RES=$(curl -# \
          -X POST \
          -H "Authorization: token $TOKEN" \
          -d "{\"tag_name\": \"$TAG\", \"name\": \"Flutter $TAG\"}" \
          "https://api.github.com/repos/$OWNER/$REPO/releases" )
ID=$(echo $RES | jq ".id")
fi

if [ $ID == 'null' ]; then
    2>&1 echo "error create new release with tag $TAG"
    2>&1
    2>&1 echo $RES
    exit -1
fi

echo "Done with $ID."

update() {
    curl -# \
         -H "Authorization: token $TOKEN" \
         -H "Content-Type: $(file -b --mime-type $2)" \
         --data-binary @$2 \
         "https://uploads.github.com/repos/$OWNER/$REPO/releases/$1/assets?name=$(basename $2)" \
    > /dev/null
}

#echo "Updating engine."
#update $ID "$ASSET/engine.sha256"
#update $ID "$ASSET/engine.tar.gz"
#echo "Updating dart-sdk."
#update $ID "$ASSET/dart-sdk.sha256"
#update $ID "$ASSET/dart-sdk.tar.gz"

update $ID "$ASSET/flutter.deb"
